### ISSUE TITLE
Panic when applying migrations during `project init` if existing instance schema not empty

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-cli#1076]
- EdgeDB Version: 2.16 (also reproduces on EdgeDB 4.0-dev.7588+local)
- EdgeDB CLI Version: 3.2.0-dev (also 3.1.2+d938bbc)
- OS Version: WSL 2 (also macOS)

Steps to Reproduce:
```
$ edgedb instance create
Specify a name for the new instance:
> pgvectest
Downloading package...
00:00:08 [====================] 35.00 MiB/35.00 MiB 3.96 MiB/s | ETA: 0s
Successfully installed 2.16+a95c8e1
Initializing EdgeDB instance...
...
Instance pgvectest is up and running.
To connect to the instance run:
  edgedb -I pgvectest

$ edgedb project init
No `edgedb.toml` found in `/home/james/pgvector_test` or above
Do you want to initialize a new project? [Y/n]
> Y
Specify the name of EdgeDB instance to use with this project [default: pgvector_test]:
> pgvectest
Do you want to use existing instance "pgvectest" for the project? [y/n]
> y
Applying migrations...
Everything is up to date. Revision initial
Project linked
To connect to pgvectest, run `edgedb`

$ edgedb project unlink
Unlinking instance pgvectest
$ rm -r dbschema/ && rm edgedb.toml

$ edgedb -I pgvectest
EdgeDB 2.16+a95c8e1 (repl 3.2.0-dev)
Type \help for help, \quit to quit.
edgedb> create type Test;
OK: CREATE TYPE
edgedb>

$ edgedb project init
No `edgedb.toml` found in `/home/james/pgvector_test` or above
Do you want to initialize a new project? [Y/n]
> Y
Specify the name of EdgeDB instance to use with this project [default: pgvector_test]:
> pgvectest
Do you want to use existing instance "pgvectest" for the project? [y/n]
> y
Applying migrations...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/migrations/migrate.rs:214:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:778:21
   4: edgedb::migrations::migrate::_migrate::{{closure}}::{{closure}}
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/migrations/migrate.rs:214:41
   5: core::option::Option<T>::unwrap_or_else
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:828:21
   6: edgedb::migrations::migrate::_migrate::{{closure}}
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/migrations/migrate.rs:213:34
   7: edgedb::migrations::migrate::migrate::{{closure}}
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/migrations/migrate.rs:120:46
   8: edgedb::portable::project::migrate_async::{{closure}}
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:1013:11
   9: edgedb::portable::project::migrate::{{closure}}
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:930:41
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/park.rs:283:63
  11: tokio::runtime::coop::with_budget
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/park.rs:283:31
  14: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/context.rs:315:13
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  16: tokio::runtime::runtime::Runtime::block_on
             at /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/runtime.rs:304:45
  17: edgedb::portable::project::migrate
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:930:5
  18: edgedb::portable::project::do_link
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:401:9
  19: edgedb::portable::project::init_new
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:773:16
  20: edgedb::portable::project::init
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/project.rs:311:17
  21: edgedb::portable::main::project_main
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/portable/main.rs:68:20
  22: edgedb::commands::cli::main
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/commands/cli.rs:71:13
  23: edgedb::_main
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/main.rs:137:9
  24: edgedb::main
             at /home/james/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/cb53629/src/main.rs:53:11
  25: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tailhook** [comment]
Fixing panic in #1077, but I'm still not sure what the best error message is and what suggestion is to give to such users.
