### ISSUE TITLE
\e panics CLI (clap regression)

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#1152]
Running `\e` now panics the CLI. Pretty sure this is a clap-related regression

```
edgedb> \e
thread 'tokio-runtime-worker' panicked at 'edit:entry: `Arg::trailing_var_arg` must accept multiple values', /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/debug_asserts.rs:548:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: clap_builder::builder::debug_asserts::assert_app
   3: clap_builder::builder::command::Command::_build_self
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/command.rs:3985:13
   4: clap_builder::builder::command::Command::_build_subcommand
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/command.rs:4072:9
   5: clap_builder::parser::parser::Parser::parse_subcommand
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/parser/parser.rs:679:27
   6: clap_builder::parser::parser::Parser::get_matches_with
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/parser/parser.rs:458:17
   7: clap_builder::builder::command::Command::_do_parse
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/command.rs:3862:29
   8: clap_builder::builder::command::Command::try_get_matches_from_mut
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/command.rs:791:9
   9: clap_builder::builder::command::Command::try_get_matches_from
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/builder/command.rs:709:9
  10: edgedb::commands::backslash::parse
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/backslash.rs:439:5
  11: edgedb::interactive::execute_backslash::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:231:21
  12: edgedb::interactive::_interactive_main::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/select.rs:524:49
  13: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/future/poll_fn.rs:58:9
  14: edgedb::interactive::_interactive_main::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:551:25
  15: edgedb::interactive::_main::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:168:51
  16: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  18: tokio::runtime::task::core::Core<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  22: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  23: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  24: tokio::runtime::task::harness::poll_future
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  25: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  26: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  27: tokio::runtime::task::raw::RawTask::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  28: tokio::runtime::task::LocalNotified<S>::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:18
  30: tokio::runtime::coop::with_budget
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  31: tokio::runtime::coop::budget
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  33: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  34: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  37: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  39: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::Core<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  45: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  46: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  47: tokio::runtime::task::harness::poll_future
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  48: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  49: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  50: tokio::runtime::task::raw::RawTask::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  51: tokio::runtime::task::UnownedTask<S>::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  52: tokio::runtime::blocking::pool::Task::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  53: tokio::runtime::blocking::pool::Inner::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  54: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by msullivan** [comment]
Running `\set output-format default` also breaks:
```
edgedb> \set output-format default
thread 'tokio-runtime-worker' panicked at 'Mismatch between definition and access of `value`. Could not downcast to edgedb::repl::OutputFormat, need to downcast to alloc::string::String
', src/commands/parser.rs:251:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: clap_builder::parser::error::MatchesError::unwrap
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/parser/error.rs:32:9
   3: clap_builder::parser::matches::arg_matches::ArgMatches::remove_one
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/parser/matches/arg_matches.rs:405:9
   4: <edgedb::commands::parser::OutputFormat as clap_builder::derive::FromArgMatches>::from_arg_matches_mut
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:246:10
   5: <edgedb::commands::parser::Setting as clap_builder::derive::FromArgMatches>::from_arg_matches_mut
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:174:10
   6: <edgedb::commands::parser::SetCommand as clap_builder::derive::FromArgMatches>::from_arg_matches_mut
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:170:15
   7: <edgedb::commands::parser::BackslashCmd as clap_builder::derive::FromArgMatches>::from_arg_matches_mut
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:142:10
   8: <edgedb::commands::parser::Backslash as clap_builder::derive::FromArgMatches>::from_arg_matches_mut
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:138:15
   9: <edgedb::commands::parser::Backslash as clap_builder::derive::FromArgMatches>::from_arg_matches
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/parser.rs:135:10
  10: edgedb::commands::backslash::parse::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/backslash.rs:441:23
  11: core::result::Result<T,E>::and_then
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1319:22
  12: edgedb::commands::backslash::parse
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/commands/backslash.rs:439:5
  13: edgedb::interactive::execute_backslash::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:231:21
  14: edgedb::interactive::_interactive_main::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/select.rs:524:49
  15: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/future/poll_fn.rs:58:9
  16: edgedb::interactive::_interactive_main::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:551:25
  17: edgedb::interactive::_main::{{closure}}
             at /home/sully/.cargo/git/checkouts/edgedb-cli-6a9c62fe43dd9873/59f8064/src/interactive.rs:168:51
  18: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  20: tokio::runtime::task::core::Core<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  21: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  23: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  24: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  25: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  26: tokio::runtime::task::harness::poll_future
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  27: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  28: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  29: tokio::runtime::task::raw::RawTask::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  30: tokio::runtime::task::LocalNotified<S>::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:18
  32: tokio::runtime::coop::with_budget
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  33: tokio::runtime::coop::budget
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  35: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  36: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  37: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  38: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  39: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  40: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  41: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  42: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  43: tokio::runtime::task::core::Core<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  44: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  47: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  48: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  49: tokio::runtime::task::harness::poll_future
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  51: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  52: tokio::runtime::task::raw::RawTask::poll
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  53: tokio::runtime::task::UnownedTask<S>::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  54: tokio::runtime::blocking::pool::Task::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  55: tokio::runtime::blocking::pool::Inner::run
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  56: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/sully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
edgedb error: task 130 panicked
```
