### ISSUE TITLE
panics if unavailable install method is used with --non-interactive

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#317]
- EdgeDB Version: N/A
- EdgeDB CLI Version: master (a7f5b9b114991085dd25fe8219cf4090226f5362)
- OS Version: Linux 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

EdgeDB packages are not currently available for my OS (Ubuntu 21.04).

```bash
$ cargo run --manifest-path ~/src/edgedb-cli/Cargo.toml -- project init --server-install-method package --non-interactive
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/home/fmoor/src/edgedb-cli/target/debug/edgedb project init --server-install-method package --non-interactive`
Found `edgedb.toml` in `/tmp/project-a`
thread 'main' panicked at 'chosen method works', src/project/init.rs:304:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   3: core::option::Option<T>::expect
             at /home/fmoor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: edgedb::project::init::init_existing
             at /home/fmoor/src/edgedb-cli/src/project/init.rs:304:16
   5: edgedb::project::init::init
             at /home/fmoor/src/edgedb-cli/src/project/init.rs:265:9
   6: edgedb::project::main::main
             at /home/fmoor/src/edgedb-cli/src/project/main.rs:10:20
   7: edgedb::commands::cli::main
             at /home/fmoor/src/edgedb-cli/src/commands/cli.rs:47:13
   8: edgedb::_main
             at /home/fmoor/src/edgedb-cli/src/main.rs:108:9
   9: edgedb::main
             at /home/fmoor/src/edgedb-cli/src/main.rs:46:11
  10: core::ops::function::FnOnce::call_once
             at /home/fmoor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fmoor** [comment]
This behavior doesn't seem to have changed. I still get a panic using master as well as the latest nightly (edgedb-cli 1.0.0-beta.1+d20210503.ga13d7799e).

**Comment by tailhook** [comment]
Yes, sorry fixed only for existing `edgedb.toml` case. New PR should fix it and provide better instructions too.
